"""Initial migration

Revision ID: fc6240d91fcd
Revises: 
Create Date: 2025-12-25 22:37:59.833644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc6240d91fcd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('user_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('text_raw', sa.String(), nullable=False),
    sa.Column('prediction', sa.Integer(), nullable=False),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('text_length', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_requests_id'), 'user_requests', ['id'], unique=False)
    op.create_index(op.f('ix_user_requests_prediction'), 'user_requests', ['prediction'], unique=False)
    op.create_index(op.f('ix_user_requests_processing_time_ms'), 'user_requests', ['processing_time_ms'], unique=False)
    op.create_index(op.f('ix_user_requests_text_length'), 'user_requests', ['text_length'], unique=False)
    op.create_index(op.f('ix_user_requests_timestamp'), 'user_requests', ['timestamp'], unique=False)
    op.create_index(op.f('ix_user_requests_user_id'), 'user_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_requests_user_id'), table_name='user_requests')
    op.drop_index(op.f('ix_user_requests_timestamp'), table_name='user_requests')
    op.drop_index(op.f('ix_user_requests_text_length'), table_name='user_requests')
    op.drop_index(op.f('ix_user_requests_processing_time_ms'), table_name='user_requests')
    op.drop_index(op.f('ix_user_requests_prediction'), table_name='user_requests')
    op.drop_index(op.f('ix_user_requests_id'), table_name='user_requests')
    op.drop_table('user_requests')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
